### ISSUE TITLE
Composer / Packagist

### ISSUE THREAD

**Issue by RamonSmit** [Spryng/SpryngApiHttpPhp#1]
The package cannot be installed trough composer because it's not registered at [Packagist](https://packagist.org/). Please consider registering the package at Packagist

**Comment by charlesbeaumont** [comment]
Hi Ramon, thanks for the tip, will do! @Roemerb, could you have a look into it?

**Comment by RamonSmit** [comment]
Still can't install the package trough composer. Please consider adding the package to Packagist or remove the composer lines from the readme

**Comment by Roemerb** [comment]
@RamonSmit @lillehummer Hi Ramon. You are right. I've informed the product owner a few weeks ago but apparently they haven't fixed it yet..

**Comment by RamonSmit** [comment]
@Roemerb It's such a simple thing to do. Just a copy-paste..

**Comment by Roemerb** [comment]
@RamonSmit I agree fully! I don't have access to their company Packagist account though.. Requested again!

**Comment by RamonSmit** [comment]
@Roemerb Great! Can't wait till the magic happens 😄

**Comment by Roemerb** [comment]
@RamonSmit I'll let you know!

**Comment by Roemerb** [comment]
@RamonSmit The package is available on Packagist.

**Comment by RamonSmit** [comment]
Hooray! Took almost 2 months, but the end result is here finally! :confetti_ball:
